{
    'name': 'Odoo Microsoft Teams Connector',
    'author': 'Softhealer Technologies',
    "license": "OPL-1",    
    'website': 'https://softhealer.com',
    "support": "support@softhealer.com",
    "version": "19.0.2.0.0",
    'category': 'Discuss',
    'summary': 'Microsoft Teams Calendar connector Join microsoft teams meetings schedule online meeting from Odoo calendar join online meetings from Odoo calendar Microsoft Teams Integration Outlook Calendar Integration Teams Meeting Outlook Meeting Microsoft teams odoo integration msteam connector ms team connector microsoft meeting integration with odoo activity to Microsoft Teams Bidirectional sync Microsoft Teams calendar sync meeting with odoo export meeting from odoo to ms team task sync Teams odoo microsoft teams integration odoo microsoft teams connector odoo microsoft team connector odoo microsoft team integration ms team integration ms team connector ms teams integration ms teams connector ms teams calendar sync outlook meeting scheduler online video conference appointment manager office 365 real time synchronization two way connection automated event creation remote work collaboration tools virtual meetings business productivity azure graph api seamless integration create update delete teams meetings directly from odoo interface schedule management planner organizer digital workplace solution team communication cloud meetings link generator secure authentication one click join efficient scheduling workflow automation instant synchronization cross platform calendar support features online collaboration suite meeting coordinator time management connect odoo with microsoft teams',
    'description': """This module allows you to schedule and manage Microsoft Teams meetings directly from the Odoo Calendar. When a calendar event is created in Odoo, a Microsoft Teams meeting link is automatically generated and synchronized with Microsoft Outlook Calendar, and any updates or deletions made in Odoo are reflected in Teams to keep all participants informed. The module supports both automatic synchronization and manual control, giving users full flexibility in managing meetings, and also allows users to join Teams meetings directly from the Odoo event view.""",
    'depends': ['base', 'calendar', 'mail','resource', 'crm', 'sh_integration_base'],
    'data': [
        'security/ir.model.access.csv',
        'data/sh_ms_teams_cron.xml',
        'views/res_config_settings.xml',
        "views/template.xml",
        'views/res_users_views.xml',
        'views/calendar_event_views.xml',
        'views/sh_teams_webhook_views.xml',
        'views/crm_lead_views.xml',
        'views/res_company_teams_views.xml',
        'views/sh_teams_sync_log_views.xml',
        'views/menu.xml',
        'data/sh_integration_connector_data.xml',
        'data/sh_integration_entity_data.xml',
        'data/sh_integration_menu_data.xml',
    ],
    'installable': True,
    'application': False,
    'auto_install': False,
    "images": ["static/description/background.png", ],    
    "price": 40.54,
    "currency": "EUR"
}
